import Head from "next/head";
import Image from "next/image";
import { Barlow_Semi_Condensed } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Header } from "@/components/Header/Header";
import { Game } from "@/components/Game/Game";
import { AppProvider } from "@/contexts";

const BarlowSemiBold = Barlow_Semi_Condensed({
  subsets: ["latin"],
  weight: ["600", "700"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Rock,Paper,Scissors</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <AppProvider>
        <main className={BarlowSemiBold.className}>
          <section className="container-global">
            <Header />
            <Game />
          </section>
        </main>
      </AppProvider>
    </>
  );
}
